# -*- coding: utf-8 -*-
from odoo import api, fields, models


class AccountPayment(models.Model):
    _inherit = 'account.payment'

    x_studio_account_mandatory = fields.Boolean(string='Account Mandatory', related='move_id.x_studio_account_mandatory', store=True, readonly=True)
    x_studio_advance_acc_updated = fields.Boolean(string='Advance ACC Updated', related='move_id.x_studio_advance_acc_updated', store=True, readonly=True)
    x_studio_advance_payment_acc_updated = fields.Boolean(string='Advance Payment ACC Updated')
    x_studio_bank_guarantee_approved = fields.Boolean(string='Bank Guarantee Approved', related='move_id.x_studio_bank_guarantee_approved', store=True, readonly=True)
    x_studio_bank_guarantee_notification = fields.Boolean(string='Bank Guarantee Notification', related='move_id.x_studio_bank_guarantee_notification', store=True, readonly=True)
    x_studio_bank_guarantee_validation = fields.Boolean(string='Bank Guarantee Validation', related='move_id.x_studio_bank_guarantee_validation', store=True, readonly=True)
    x_studio_bg_sent = fields.Boolean(string='BG Sent', related='move_id.x_studio_bg_sent', store=True, readonly=True)
    x_studio_boolean_field_A32jc = fields.Boolean(string='New Checkbox', store=False)
    x_studio_boolean_field_E4oM7 = fields.Boolean(string='New Checkbox', store=False)
    x_studio_boolean_field_EoMg9 = fields.Boolean(string='New Checkbox', store=False)
    x_studio_boolean_field_MVlhn = fields.Boolean(string='New Checkbox', store=False)
    x_studio_boolean_field_RIlaO = fields.Boolean(string='New Checkbox', store=False)
    x_studio_boolean_field_XzV6D = fields.Boolean(string='New Checkbox', store=False)
    x_studio_boolean_field_bnVim = fields.Boolean(string='New Checkbox', store=False)
    x_studio_boolean_field_djczB = fields.Boolean(string='New Checkbox', store=False)
    x_studio_boolean_field_qcQya = fields.Boolean(string='New Checkbox', store=False)
    x_studio_boolean_field_xNbhc = fields.Boolean(string='New Checkbox', store=False)
    x_studio_boolean_field_xud0H = fields.Boolean(string='New Checkbox', store=False)
    x_studio_boolean_field_ydmJ5 = fields.Boolean(string='New Checkbox', store=False)
    x_studio_boolean_field_ygnit = fields.Boolean(string='New Checkbox', store=False)
    x_studio_char_field_FnRNH = fields.Char(string='New Text', store=False)
    x_studio_co = fields.Many2one('x_consignment_header', string='Co', store=False)
    x_studio_consignment_no = fields.Many2one('x_consignment_header', string='Consignment No', related='move_id.x_studio_consignment_no', store=True, readonly=True)
    x_studio_cre = fields.Many2one('x_purchase_request_cas', string='Created From CP No', related='move_id.x_studio_cre', store=True, readonly=True)
    x_studio_create_from_transfer = fields.Many2one('stock.picking', string='Create From Transfer', store=False)
    x_studio_create_from_transfer_1 = fields.Many2one('stock.picking', string='Create From Transfer', related='move_id.x_studio_create_from_transfer_1', store=True, readonly=True)
    x_studio_created_from_consignment = fields.Many2one('x_consignment_header', string='Created From Consignment', related='move_id.x_studio_created_from_consignment', store=True, readonly=True)
    x_studio_created_from_consignment_1 = fields.Many2one('x_consignment_header', string='Created From Consignment', related='move_id.x_studio_created_from_consignment_1', store=True, readonly=True)
    x_studio_created_from_consignment_2 = fields.Many2one('x_consignment_header', string='Created From Consignment 2', store=False)
    x_studio_created_from_npo_no = fields.Many2one('x_po_non_inventory', string='Created From NPO No', related='move_id.x_studio_created_from_npo_no', store=True, readonly=True)
    x_studio_created_from_pr_no = fields.Many2one('x_po_non_inventory', string='Created From PR No', store=False)
    x_studio_created_from_project = fields.Boolean(string='Created From Project', related='move_id.x_studio_created_from_project', store=True, readonly=True)
    x_studio_created_from_project_1 = fields.Boolean(string='Created From Project')
    x_studio_created_from_project_no = fields.Many2one('project.project', string='Created From Project No', related='move_id.x_studio_created_from_project_no', store=True, readonly=True)
    x_studio_created_from_tp_invoice = fields.Many2one('x_tp_invoice_header', string='Created From TP Invoice', store=False)
    x_studio_created_from_transfer = fields.Many2one('stock.picking', string='Created From Transfer', related='move_id.x_studio_created_from_transfer', store=True, readonly=True)
    x_studio_created_from_vendor_bill = fields.Many2one('account.move', string='Created From Vendor Bill', related='move_id.x_studio_created_from_vendor_bill', store=True, readonly=True)
    x_studio_created_from_vendor_bill_1 = fields.Many2one('account.move', string='Created From Vendor Bill', related='move_id.x_studio_created_from_vendor_bill_1', store=True, readonly=True)
    x_studio_created_transfer = fields.Many2one('stock.picking', string='Created Transfer', store=False)
    x_studio_credit_limit_approved = fields.Boolean(string='Credit Limit Approved', related='move_id.x_studio_credit_limit_approved', store=True, readonly=True)
    x_studio_credit_limit_validation = fields.Boolean(string='Credit Limit Validation', related='move_id.x_studio_credit_limit_validation', store=True, readonly=True)
    x_studio_credit_note_approved = fields.Boolean(string='Credit Note Approved', related='move_id.x_studio_credit_note_approved', store=True, readonly=True)
    x_studio_credit_note_request_sent = fields.Boolean(string='Credit Note Request Sent', related='move_id.x_studio_credit_note_request_sent', store=True, readonly=True)
    x_studio_currency_rate = fields.Float(string='Currency Rate', related='move_id.x_studio_currency_rate', store=True, readonly=True)
    x_studio_currency_rate_updated = fields.Boolean(string='Currency Rate Updated', related='move_id.x_studio_currency_rate_updated', store=True, readonly=True)
    x_studio_custom_clearance_no = fields.Char(string='Custom Clearance No', related='move_id.x_studio_custom_clearance_no', store=True, readonly=True)
    x_studio_float_field_5tma1 = fields.Float(string='New Decimal', store=False)
    x_studio_journal_type = fields.Selection([], string='Journal Type', related='move_id.x_studio_journal_type', store=True, readonly=True)
    x_studio_lc_no = fields.Many2one('x_lc_header', string='LC No', related='move_id.x_studio_lc_no', store=True, readonly=True)
    x_studio_lc_no_1 = fields.Many2one('x_lc_header', string='LC No')
    x_studio_lc_test1 = fields.Boolean(string='LC - test1', related='move_id.x_studio_lc_test1', store=True, readonly=True)
    x_studio_many2one_field_4CPvU = fields.Many2one('x_purchase_request_cas', string='Purchase  Request Cash', store=False)
    x_studio_many2one_field_6HjHy = fields.Many2one('account.move', string='Journal Entry', store=False)
    x_studio_many2one_field_6Sjmv = fields.Many2one('stock.picking', string='Transfer', store=False)
    x_studio_many2one_field_A197A = fields.Many2one('x_consignment_header', string='Consignment Header', store=False)
    x_studio_many2one_field_B4ibh = fields.Many2one('project.project', string='Project', store=False)
    x_studio_many2one_field_KKFaY = fields.Many2one('x_tp_invoice_header', string='TP Invoice Header', store=False)
    x_studio_many2one_field_L9MIu = fields.Many2one('x_sales_report_type', string='Sales Report Type', store=False)
    x_studio_many2one_field_P4o2n = fields.Many2one('project.project', string='Project', store=False)
    x_studio_many2one_field_PJkjM = fields.Many2one('x_lc_header', string='LC Header', store=False)
    x_studio_many2one_field_R46Ke = fields.Many2one('project.project', string='Project', store=False)
    x_studio_many2one_field_TEK9K = fields.Many2one('stock.picking', string='Transfer', store=False)
    x_studio_many2one_field_XhwuI = fields.Many2one('purchase.order', string='Purchase Order', store=False)
    x_studio_many2one_field_aIXMs = fields.Many2one('x_tp_invoice_header', string='TP Invoice Header', store=False)
    x_studio_many2one_field_ffAE3 = fields.Many2one('account.move', string='Journal Entry', store=False)
    x_studio_many2one_field_jslCp = fields.Many2one('x_consignment_header', string='Consignment Header', store=False)
    x_studio_many2one_field_mULOh = fields.Many2one('account.move', string='Journal Entry', store=False)
    x_studio_many2one_field_mucWu = fields.Many2one('x_consignment_header', string='Consignment Header', store=False)
    x_studio_many2one_field_re1H2 = fields.Many2one('sale.order', string='Sales Order', store=False)
    x_studio_many2one_field_rpsBC = fields.Many2one('x_po_non_inventory', string='Purchase Order (Non-Inventory)', store=False)
    x_studio_many2one_field_tpCkS = fields.Many2one('project.project', string='Project', store=False)
    x_studio_many2one_field_vAeTQ = fields.Many2one('project.project', string='Project', store=False)
    x_studio_many2one_field_xkSx5 = fields.Many2one('account.move', string='Journal Entry', store=False)
    x_studio_order_payment_method = fields.Selection([], string='Order Payment Method', related='move_id.x_studio_order_payment_method', store=True, readonly=True)
    x_studio_over_bank_guarantee = fields.Boolean(string='Over Bank Guarantee', related='move_id.x_studio_over_bank_guarantee', store=True, readonly=True)
    x_studio_payment_validation = fields.Boolean(string='Payment Validation', compute='_compute_x_studio_payment_validation', store=True, readonly=True)
    x_studio_payment_validation_1 = fields.Char(string='Payment Validation')
    x_studio_project_no = fields.Many2one('project.project', string='Project No', related='move_id.x_studio_project_no', store=True, readonly=True)
    x_studio_project_no_1 = fields.Many2one('project.project', string='Project No')
    x_studio_project_no_bill = fields.Many2one('project.project', string='Project No Bill', related='move_id.x_studio_project_no_bill', store=True, readonly=True)
    x_studio_project_no_issue = fields.Many2one('project.project', string='Project No Issue', related='move_id.x_studio_project_no_issue', store=True, readonly=True)
    x_studio_project_no_settle = fields.Many2one('project.project', string='Project No Settle', related='move_id.x_studio_project_no_settle', store=True, readonly=True)
    x_studio_project_no_settle_1 = fields.Many2one('project.project', string='Project No Settle', store=False)
    x_studio_purchase_id = fields.Many2one('purchase.order', string='Purchase Order', related='move_id.x_studio_purchase_id', store=True, readonly=True)
    x_studio_purchase_order = fields.Many2one('purchase.order', string='Purchase Order')
    x_studio_purchase_type = fields.Selection([], string='PR Type', related='move_id.x_studio_purchase_type', store=True, readonly=True)
    x_studio_quotation_type = fields.Selection([], string='Quotation Type')
    x_studio_related_field_1JsOz = fields.Boolean(string='New Related Field', readonly=True, store=False)
    x_studio_related_field_7SPn1 = fields.Boolean(string='New Related Field', readonly=True, store=False)
    x_studio_related_field_DBwI2 = fields.Selection([], string='New Related Field', readonly=True, store=False)
    x_studio_related_field_QgLxV = fields.Boolean(string='New Related Field', readonly=True, store=False)
    x_studio_related_field_T4rIR = fields.Selection([], string='New Related Field', readonly=True, store=False)
    x_studio_related_field_VMbnh = fields.Boolean(string='New Related Field', readonly=True, store=False)
    x_studio_related_field_bRYM3 = fields.Selection([], string='New Related Field', readonly=True, store=False)
    x_studio_related_field_m4xKC = fields.Selection([], string='New Related Field', readonly=True, store=False)
    x_studio_related_field_nIq3I = fields.Selection([], string='New Related Field', readonly=True, store=False)
    x_studio_related_field_nQx1u = fields.Boolean(string='New Related Field', readonly=True, store=False)
    x_studio_related_field_pSJXo = fields.Char(string='New Related Field', readonly=True, store=False)
    x_studio_related_field_v5UEx = fields.Boolean(string='New Related Field', readonly=True, store=False)
    x_studio_related_field_w1zkr = fields.Selection([], string='New Related Field', readonly=True, store=False)
    x_studio_related_field_yj3hQ = fields.Selection([], string='New Related Field', readonly=True, store=False)
    x_studio_report_type_s_cust_aging = fields.Many2one('x_sales_report_type', string='Report Type (S - Cust Aging)', related='move_id.x_studio_report_type_s_cust_aging', store=True, readonly=True)
    x_studio_rug_acc_updated = fields.Boolean(string='RUG Account Updated', related='move_id.x_studio_rug_acc_updated', store=True, readonly=True)
    x_studio_rug_confirmed = fields.Boolean(string='RUG Confirmed', related='move_id.x_studio_rug_confirmed', store=True, readonly=True)
    x_studio_rug_rejected = fields.Boolean(string='RUG Rejected', related='move_id.x_studio_rug_rejected', store=True, readonly=True)
    x_studio_sale_id = fields.Many2one('sale.order', string='Sale_Id', related='move_id.x_studio_sale_id', store=True, readonly=True)
    x_studio_sales_order = fields.Many2one('sale.order', string='Sales Order')
    x_studio_selection_field_5Gimk = fields.Selection([], string='New Selection', store=False)
    x_studio_selection_field_KlNrV = fields.Selection([], string='New Selection', store=False)
    x_studio_selection_field_N6ihz = fields.Selection([], string='New Selection', store=False)
    x_studio_supplier_invoice_number = fields.Char(string="XXX Supplier's Invoice Number (Bill Reference)", related='move_id.x_studio_supplier_invoice_number', store=True, readonly=True)
    x_studio_test_type = fields.Selection([], string='Test Type', related='move_id.x_studio_test_type', store=True, readonly=True)
    x_studio_tp_id = fields.Many2one('x_tp_invoice_header', string='Created From TP Invoice', related='move_id.x_studio_tp_id', store=True, readonly=True)
    x_studio_tp_invoice_no = fields.Many2one('x_tp_invoice_header', string='TP Invoice No')
    x_studio_type = fields.Selection([('General', 'General'), ('Advance Payment', 'Advance Payment')], string='Type')
    x_studio_update_consignment = fields.Boolean(string='Update Consignment', related='move_id.x_studio_update_consignment', store=True, readonly=True)
    x_studio_valid_lines = fields.Boolean(string='Valid Lines', related='move_id.x_studio_valid_lines', store=True, readonly=True)
    x_x_studio_created_from_vendor_bill_1__account_move_count = fields.Integer(string='Created From Vendor Bill count', related='move_id.x_x_studio_created_from_vendor_bill_1__account_move_count', store=True, readonly=True)
    x_x_studio_created_from_vendor_bill__account_move_count = fields.Integer(string='Created From Vendor Bill count', related='move_id.x_x_studio_created_from_vendor_bill__account_move_count', store=True, readonly=True)

    @api.depends('x_studio_quotation_type', 'x_studio_sales_order', 'amount')
    def _compute_x_studio_payment_validation(self):
        # Ported from CDB Studio compute (bugfix_sales:config-cutover-v22).
        # Minimal semantics: True when a sales_order link exists AND amount > 0.
        for rec in self:
            has_so = bool(getattr(rec, 'x_studio_sales_order', False))
            rec.x_studio_payment_validation = has_so and (rec.amount or 0) > 0

