# -*- coding: utf-8 -*-
from odoo import fields, models


class AccountMoveLine(models.Model):
    _inherit = 'account.move.line'

    x_studio_aaa = fields.Char(string='AAA', readonly=True, store=False)
    x_studio_account_mandatory = fields.Boolean(string='Account Mandatory')
    x_studio_analytic_group = fields.Many2one('account.analytic.plan', string='Analytic Group')
    x_studio_beneficiary_id = fields.Char(string='Beneficiary ID', readonly=True)
    x_studio_beneficiary_name = fields.Char(string='Beneficiary Name', readonly=True)
    x_studio_category = fields.Many2one('x_project_category', string='Category')
    x_studio_contract_id = fields.Many2one('hr.contract', string='Contract Id')
    x_studio_credit_limit = fields.Float(string='Credit Limit', readonly=True)
    x_studio_credit_limit_2 = fields.Float(string='Credit Limit 2', readonly=True)
    x_studio_customer_group_type = fields.Selection([], string='Customer Group Type', readonly=True)
    x_studio_employers_contribution = fields.Float(string="Employer's Contribution", readonly=True, store=False)
    x_studio_epf_number = fields.Char(string='EPF Number', readonly=True)
    x_studio_etf_number = fields.Char(string='ETF Number', readonly=True)
    x_studio_initials = fields.Char(string='Initials', readonly=True)
    x_studio_invoice_date = fields.Date(string='Invoice Date', readonly=True)
    x_studio_journal = fields.Many2one('account.move', string='Journal', readonly=True)
    x_studio_journal_type = fields.Selection([], string='Journal Type', readonly=True)
    # x_studio_many2one_field_kiSUJ moved to studio_usermodel_migration
    # (Jinasena : Masterdata : User) in v0.0.33. See account_move.py note.
    x_studio_members_contribution = fields.Float(string="Member's Contribution", readonly=True, store=False)
    x_studio_nic_number = fields.Char(string='NIC Number', readonly=True)
    x_studio_occupation_code = fields.Char(string='New Related Field', readonly=True)
    x_studio_partner = fields.Many2one('res.partner', string='Partner', readonly=True)
    x_studio_payment_status = fields.Selection([], string='Payment Status', readonly=True)
    x_studio_pr_type = fields.Selection([], string='PR Type', readonly=True)
    x_studio_product_category = fields.Many2one('product.category', string='Product Category', readonly=True, store=False)
    x_studio_project_no = fields.Many2one('project.project', string='Project No', readonly=True)
    x_studio_purchase_order = fields.Char(string='Purchase Order', readonly=True)
    x_studio_purpose_code = fields.Char(string='Purpose Code', readonly=True)
    x_studio_related_field_5LBku = fields.Char(string='New Related Field', readonly=True, store=False)
    x_studio_related_field_5j5_1isv2aad6 = fields.Char(string='New Related Field', readonly=True)
    x_studio_related_field_CQ41C = fields.Many2one('product.product', string='New Related Field', readonly=True, store=False)
    x_studio_related_field_CvPMn = fields.Char(string='New Related Field', readonly=True, store=False)
    x_studio_related_field_FWW4G = fields.Float(string='New Related Field', readonly=True)
    x_studio_related_field_HFHrh = fields.Char(string='New Related Field', readonly=True, store=False)
    x_studio_related_field_HO3gE = fields.Char(string='New Related Field', readonly=True, store=False)
    x_studio_related_field_MnJZJ = fields.Char(string='New Related Field', readonly=True, store=False)
    x_studio_related_field_Nf3SX = fields.Float(string='New Related Field', readonly=True)
    x_studio_related_field_SORzX = fields.Integer(string='New Related Field', readonly=True)
    x_studio_related_field_VzwUx = fields.Integer(string='New Related Field', readonly=True)
    x_studio_related_field_WVIs6 = fields.Char(string='New Related Field', readonly=True)
    x_studio_related_field_X2pdt = fields.Float(string='New Related Field', readonly=True)
    x_studio_related_field_aD9tj = fields.Float(string='New Related Field', readonly=True)
    x_studio_related_field_e9NHB = fields.Char(string='New Related Field', readonly=True)
    x_studio_related_field_kbp8y = fields.Char(string='New Related Field', readonly=True, store=False)
    x_studio_related_field_lBjdh = fields.Float(string='New Related Field', readonly=True, store=False)
    # TODO: x_studio_related_field_zy8mz = fields.One2many(...) -- Studio inverse name unknown; port from Clear-DB manually.
    # x_studio_sales_report_type moved to studio_usermodel_migration
    # (Jinasena : Masterdata : User) in v0.0.33. See account_move.py note.
    x_studio_sales_team = fields.Many2one('crm.team', string='Sales Team', readonly=True)
    x_studio_status = fields.Selection([], string='Status', readonly=True)
    x_studio_status_1 = fields.Selection([], string='Status', readonly=True)
    x_studio_surname = fields.Char(string='Surname', readonly=True)
    x_studio_swift_code = fields.Char(string='Swift Code', readonly=True)
    x_studio_tags = fields.Many2many('x_misc_charge_codes', 'account_move_line_x_studio_tags_rel', 'account_id', 'x_misc_charge_codes_id', string='Tags')
    x_studio_tax = fields.Float(string='Tax', readonly=True)  # was Monetary (no currency_field)
    x_studio_to_account = fields.Char(string='To Account', readonly=True)
    x_studio_total_contribution = fields.Float(string='Total Contribution', readonly=True, store=False)
    x_studio_total_earnings = fields.Float(string='Total Earnings', readonly=True)  # was Monetary (no currency_field)